# docker-compose.yml
version: "3.5"

services:
  app-golang:
    image: golang:1.14
    restart: always
    volumes:
      - .:/go/src/authenName
    working_dir: /go/src/authenName
    ports:
    - 3001:8080
    command: go run main.go