# docker-compose.yml
version: "3.5"

services:
  app-golang:
    # image
    build:
      context: .
    restart: always
    volumes:
      - .:/go/src/authenName
    working_dir: /go/src/authenName
    ports:
      - 3001:3001
    command: go run main.go
